language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rym' ]; then cd .. && eval "mv $currentfolder generator-rym" && cd generator-rym; fi

